apiVersion: v1
kind: Pod
metadata:
  name: adopted-b
  namespace: dev
  labels:
    app: rs-adopt-demo
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
