# 02-replicaset/rs-nginx.yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata: { name: rs-nginx, namespace: dev }
spec:
  replicas: 2
  selector: { matchLabels: { app: web } }
  template:
    metadata: { labels: { app: web } }
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
