apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello-app-pod
  namespace: dev
spec:
  containers:
    - name: api
      image: ghcr.io/hello-world-go:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
