apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: dev
  labels:
    app: label-app
spec:
  containers:
    - name: hello
      image: nginx:1.25
      ports:
        - containerPort: 80
