apiVersion: v1
kind: Service
metadata:
  name: mysql-hl
  namespace: dev
  labels:
    app: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306