apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: dev
data:
  custom.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
    sql_mode = NO_ENGINE_SUBSTITUTION
    max_connections = 100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: dev
data:
  01_schema.sql: |
    CREATE DATABASE IF NOT EXISTS appdb;
    CREATE TABLE IF NOT EXISTS appdb.visits (
      id INT AUTO_INCREMENT PRIMARY KEY,
      ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
  02_user.sql: |
    CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'appsecret';
    GRANT ALL PRIVILEGES ON appdb.* TO 'appuser'@'%';
    FLUSH PRIVILEGES;
