apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: http
      port: 80        # service port
      targetPort: 80  # pod port
      nodePort: 30080 # fixed node port (optional)
