apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      port: 8081        # Service port
      targetPort: 80  # Must match containerPort in Deployment
